[package]
name = "delila"
version = "0.1.0"
authors = ["Lakin Wecker <lakin@structuredabstraction.com>"]

[dependencies]
samson = { git = "ssh://git@github.com/lakinwecker/samson.git" }
diesel = { version = "0.9.0", features = ["chrono"] }
diesel_codegen = { version = "0.9.0", features = ["sqlite"] }
dotenv = "0.8.0"
rocket = "0.1.5"
rocket_codegen = "0.1.5"
rocket_contrib = "0.1.5"
serde = "0.8.22"
serde_json = "0.8.4"
serde_derive = "0.8.22"
error-chain = "0.7.2"
