[package]
name = "delila"
version = "0.1.0"
authors = ["Lakin Wecker <lakin@structuredabstraction.com>"]

[dependencies]
samson = { git = "ssh://git@github.com/lakinwecker/samson.git" }
diesel = { version = "0.9.0", features = ["chrono"] }
diesel_codegen = { version = "0.9.0", features = ["sqlite"] }
dotenv = "0.8.0"
rocket = "0.2.2"
rocket_codegen = "0.2.2"
rocket_contrib = "0.2.2"
serde = "0.9.11"
serde_json = "0.9.9"
serde_derive = "0.9.11"
error-chain = "0.10.0"
ws = "0.6.0"
