[package]
name = "delila"
version = "0.1.0"
authors = ["Lakin Wecker <lakin@structuredabstraction.com>"]

[dependencies]
samson = { git = "https://github.com/lakinwecker/samson.git" }
diesel = { version = "0.13.0", features = ["chrono", "sqlite"] }
diesel_codegen = { version = "0.13.0", features = ["sqlite"] }
dotenv = "0.9.0"
serde = "1.0.7"
serde_json = "1.0.1"
serde_derive = "1.0.7"
error-chain = "0.10.0"
ws = "0.7.1"
futures = "0.1.13"
futures-cpupool = "0.1.5"
